obj-y += cpupool.o
obj-$(CONFIG_SCHED_ARINC653) += sched_arinc653.o
obj-$(CONFIG_SCHED_CREDIT) += sched_credit.o
obj-$(CONFIG_SCHED_CREDIT2) += sched_credit2.o
obj-$(CONFIG_SCHED_RTDS) += sched_rt.o
obj-$(CONFIG_SCHED_NULL) += sched_null.o
obj-y += schedule.o
