/*
 * xen/common/efi/pe.c
 *
 * PE executable header parser.
 *
 * Derived from https://github.com/systemd/systemd/blob/master/src/boot/efi/pe.c
 *
 * Copyright (C) 2015 Kay Sievers <kay@vrfy.org>
 * Copyright (C) 2020 Trammell Hudson <hudson@trmm.net>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 */

/*
 * The "Unified" kernel image can be generated by adding additional
 * sections to the Xen EFI executable with objcopy, similar to how
 * systemd-boot uses the stub to add them to the Linux kernel:
 *
 * https://wiki.archlinux.org/index.php/systemd-boot#Preparing_a_unified_kernel_image
 *
 * The sections for the xen configuration file, the dom0 kernel, dom0 initrd,
 * XSM and CPU microcode should be added after the Xen `.pad` section, the
 * ending address of which can be located with:
 *
 *	objdump -h xen.efi \
 *	| perl -ane '/\.pad/ && printf "0x%016x\n", hex($F[2]) + hex($F[3])'
 *
 * All the additional sections are optional and the order does not
 * matter.  The addresses do not need to be contiguous, although
 * they should not be overlapping.
 *
 * objcopy \
 *	--add-section .config=xen.cfg \
 *	--change-section-vma .config=0xffff82d041000000
 *	--add-section .ucode=ucode.bin \
 *	--change-section-vma .ucode=0xffff82d041010000 \
 *	--add-section .xsm=xsm.cfg \
 *	--change-section-vma .xsm=0xffff82d041080000 \
 *	--add-section .kernel=vmlinux \
 *	--change-section-vma .kernel=0xffff82d041100000 \
 *	--add-section .ramdisk=initrd.img \
 *	--change-section-vma .initrd=0xffff82d042000000 \
 *	xen.efi \
 *	xen.unified.efi
 *
 * The unified executable can be signed with sbsigntool to make
 * it usable with UEFI secure boot:
 *
 * sbsign \
 *	--key signing.key \
 *	--cert cert.pem \
 *	--output xen.signed.efi \
 *	xen.unified.efi
 */

#include "efi.h"

struct DosFileHeader {
    UINT8   Magic[2];
    UINT16  LastSize;
    UINT16  nBlocks;
    UINT16  nReloc;
    UINT16  HdrSize;
    UINT16  MinAlloc;
    UINT16  MaxAlloc;
    UINT16  ss;
    UINT16  sp;
    UINT16  Checksum;
    UINT16  ip;
    UINT16  cs;
    UINT16  RelocPos;
    UINT16  nOverlay;
    UINT16  reserved[4];
    UINT16  OEMId;
    UINT16  OEMInfo;
    UINT16  reserved2[10];
    UINT32  ExeHeader;
} __attribute__((packed));

#define PE_HEADER_MACHINE_ARM64         0xaa64
#define PE_HEADER_MACHINE_X64           0x8664
#define PE_HEADER_MACHINE_I386          0x014c

struct PeFileHeader {
    UINT16  Machine;
    UINT16  NumberOfSections;
    UINT32  TimeDateStamp;
    UINT32  PointerToSymbolTable;
    UINT32  NumberOfSymbols;
    UINT16  SizeOfOptionalHeader;
    UINT16  Characteristics;
} __attribute__((packed));

struct PeHeader {
    UINT8   Magic[4];
    struct PeFileHeader FileHeader;
} __attribute__((packed));

struct PeSectionHeader {
    UINT8   Name[8];
    UINT32  VirtualSize;
    UINT32  VirtualAddress;
    UINT32  SizeOfRawData;
    UINT32  PointerToRawData;
    UINT32  PointerToRelocations;
    UINT32  PointerToLinenumbers;
    UINT16  NumberOfRelocations;
    UINT16  NumberOfLinenumbers;
    UINT32  Characteristics;
} __attribute__((packed));

const void * __init pe_find_section(const CHAR8 * image, const UINTN image_size,
                              const char * section_name, UINTN * size_out)
{
    const struct DosFileHeader * dos = (const void*) image;
    const struct PeHeader * pe;
    const struct PeSectionHeader * sect;
    const UINTN name_len = strlen(section_name);
    UINTN offset = 0;

    if ( name_len > sizeof(sect->Name) )
        return NULL;

    if ( image_size < sizeof(*dos) )
        return NULL;
    if ( memcmp(dos->Magic, "MZ", 2) != 0 )
        return NULL;

    offset = dos->ExeHeader;
    pe = (const void *) &image[offset];

    offset += sizeof(*pe);
    if ( image_size < offset)
        return NULL;

    if ( memcmp(pe->Magic, "PE\0\0", 4) != 0 )
        return NULL;

    /* PE32+ Subsystem type */
#if defined(__ARM__)
    if (pe->FileHeader.Machine != PE_HEADER_MACHINE_ARM64)
        return NULL;
#elif defined(__x86_64__)
    if (pe->FileHeader.Machine != PE_HEADER_MACHINE_X64)
        return NULL;
#else
    /* unknown architecture */
    return NULL;
#endif

    offset += pe->FileHeader.SizeOfOptionalHeader;

    for (UINTN i = 0 ; i < pe->FileHeader.NumberOfSections ; i++)
    {
        sect = (const void *) &image[offset];
        if ( image_size < offset + sizeof(*sect) )
            return NULL;

        if ( memcmp(sect->Name, section_name, name_len) != 0
        ||   image_size < sect->VirtualSize + sect->VirtualAddress )
        {
            offset += sizeof(*sect);
            continue;
        }

        if ( size_out )
            *size_out = sect->VirtualSize;

        return &image[sect->VirtualAddress];
    }

    return NULL;
}
